### ISSUE TITLE
obstacles to getting ootb-basic-supply-chain with python working

### ISSUE THREAD

**Issue by Analect** [vrabbi/tap-oss#5]
Looking to get `ootb-basic-supply-chain` running for the python example.
It appears the workload is `Ready`.
```
kubectl get workload
NAME              SOURCE                                          SUPPLYCHAIN               READY     REASON
go-demo-app       https://github.com/kontinue/hello-world         ootb-basic-supply-chain   Unknown   MissingValueAtPath
python-demo-app   https://github.com/vrabbi/python-demo-app.git   ootb-basic-supply-chain   True      Ready
```
... and that a relevant image has been built ... 
```
kubectl get cnbimage,build
NAME                             LATESTIMAGE                                                                                                                 READY
image.kpack.io/go-demo-app                                                                                                                                   False
image.kpack.io/python-demo-app   registry.local:5000/workloads/oss-python-demo-app@sha256:8152f12d18c19c34d7a0efd722d8ae0f710bae8179af6070908a83cb98fefda6   True

NAME                                     IMAGE                                                                                                                       SUCCEEDED
build.kpack.io/go-demo-app-build-1                                                                                                                                   False
build.kpack.io/python-demo-app-build-1   registry.local:5000/workloads/oss-python-demo-app@sha256:8152f12d18c19c34d7a0efd722d8ae0f710bae8179af6070908a83cb98fefda6   True
```
... and is available in the registry

![image](https://user-images.githubusercontent.com/4063815/154803542-73a1dae1-ee27-4708-9150-6aacbceaa0b7.png)

... but the python app itself is having issues.
```
[2022-02-19 12:25:27 +0000] [1] [INFO] Starting gunicorn 19.5.0
[2022-02-19 12:25:27 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
[2022-02-19 12:25:27 +0000] [1] [INFO] Using worker: sync
/layers/paketo-buildpacks_cpython/cpython/lib/python3.8/os.py:1023: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  return io.open(fd, *args, **kwargs)
[2022-02-19 12:25:27 +0000] [17] [INFO] Booting worker with pid: 17
[2022-02-19 12:25:31 +0000] [17] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/layers/paketo-buildpacks_pip-install/packages/lib/python3.8/site-packages/gunicorn/arbiter.py", line 517, in spawn_worker
    worker.init_process()
  File "/layers/paketo-buildpacks_pip-install/packages/lib/python3.8/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/layers/paketo-buildpacks_pip-install/packages/lib/python3.8/site-packages/gunicorn/workers/base.py", line 132, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/layers/paketo-buildpacks_pip-install/packages/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/layers/paketo-buildpacks_pip-install/packages/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/layers/paketo-buildpacks_pip-install/packages/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/layers/paketo-buildpacks_pip-install/packages/lib/python3.8/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/workspace/server.py", line 2, in <module>
    from flask import Flask, render_template
  File "/layers/paketo-buildpacks_pip-install/packages/lib/python3.8/site-packages/flask/__init__.py", line 21, in <module>
    from .app import Flask, Request, Response
  File "/layers/paketo-buildpacks_pip-install/packages/lib/python3.8/site-packages/flask/app.py", line 26, in <module>
    from . import json, cli
  File "/layers/paketo-buildpacks_pip-install/packages/lib/python3.8/site-packages/flask/json/__init__.py", line 21, in <module>
    from itsdangerous import json as _json
ImportError: cannot import name 'json' from 'itsdangerous' (/layers/paketo-buildpacks_pip-install/packages/lib/python3.8/site-packages/itsdangerous/__init__.py)
[2022-02-19 12:25:31 +0000] [17] [INFO] Worker exiting (pid: 17)
/layers/paketo-buildpacks_cpython/cpython/lib/python3.8/os.py:1023: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  return io.open(fd, *args, **kwargs)
[2022-02-19 12:25:31 +0000] [1] [INFO] Shutting down: Master
[2022-02-19 12:25:31 +0000] [1] [INFO] Reason: Worker failed to boot.
```
Any suggestions around troubleshooting this greatly appreciated. Thanks.

**Comment by Analect** [comment]
Seems the problem lies with the version of flask in [requirments.txt](https://github.com/vrabbi/python-demo-app/blob/master/requirements.txt).   Running locally with these settings appears to work.  See https://serverfault.com/questions/1094062

```
Flask==1.1.4
Jinja2
MarkupSafe==2.0.1
Werkzeug
gunicorn
```

![image](https://user-images.githubusercontent.com/4063815/154854183-ae4a4bc6-4688-4c26-968a-b0a7cf3bbd2f.png)
